import type { BudgetSegment, BudgetSegmentType } from "./types"

export const DEFAULT_SEGMENTS: Record<BudgetSegmentType, BudgetSegment[]> = {
  fund: [
    { code: "01", title: "General Fund" },
    { code: "02", title: "Food Service Fund" },
    { code: "04", title: "Community Service Fund" },
    { code: "05", title: "Capital (Local Orono Code)" },
    { code: "06", title: "Building Construction Fund" },
    { code: "07", title: "Debt Service Fund" },
    { code: "18", title: "Custodial Fund" },
    { code: "20", title: "Internal Service Fund" },
    { code: "45", title: "OPEB Irrevocable Trust Fund" },
    { code: "50", title: "Student Activities (Local Orono Code)" },
  ],
  org: [
    { code: "005", title: "Districtwide" },
    { code: "030", title: "High School" },
    { code: "031", title: "Middle School" },
    { code: "100", title: "Elementary School" },
    { code: "200", title: "Elementary/Secondary (Combined)" },
    { code: "205", title: "Summer School" },
    { code: "206", title: "Summer Programs" },
    { code: "300", title: "Secondary" },
    { code: "661", title: "Schumann Elementary" },
    { code: "662", title: "Intermediate School" },
    { code: "700", title: "Holy Name Non-Public" },
    { code: "799", title: "Home Schools" },
    { code: "998", title: "Tuition Billing Site" },
  ],
  proj: [
    { code: "010", title: "School Board" },
    { code: "020", title: "Superintendent" },
    { code: "050", title: "School Administration" },
    { code: "106", title: "Human Resources" },
    { code: "107", title: "Other Admin" },
    { code: "108", title: "Admin Tech Services" },
    { code: "110", title: "Business Office" },
    { code: "130", title: "Communications" },
    { code: "140", title: "Registration" },
    { code: "203", title: "Elementary Education" },
    { code: "211", title: "Secondary Education" },
    { code: "212", title: "Visual Art" },
    { code: "218", title: "Gifted & Talented" },
    { code: "220", title: "Lang Arts" },
    { code: "230", title: "World Language" },
    { code: "240", title: "Phys Ed" },
    { code: "255", title: "Technology Ed" },
    { code: "256", title: "Math" },
    { code: "258", title: "Band" },
    { code: "259", title: "Choral" },
    { code: "260", title: "Natural Science" },
    { code: "270", title: "Social Science" },
    { code: "291", title: "Co-Curricular" },
    { code: "292", title: "General Athletics" },
    { code: "294", title: "Boys Athletics" },
    { code: "296", title: "Girls Athletics" },
    { code: "400", title: "Special Ed General" },
    { code: "401", title: "Speech/Language" },
    { code: "402", title: "DCD-MM (Mild-Moderate)" },
    { code: "403", title: "DCD-SEV (Severe)" },
    { code: "407", title: "Specific Learning Disability" },
    { code: "408", title: "EBD (Emotional Behavioral)" },
    { code: "410", title: "Other Health Disabilities" },
    { code: "411", title: "Autistic" },
    { code: "423", title: "Adaptive PE" },
    { code: "505", title: "Community Ed - General" },
    { code: "560", title: "Adult Enrichment" },
    { code: "561", title: "Aquatics" },
    { code: "570", title: "School Age Care" },
    { code: "580", title: "ECFE" },
    { code: "582", title: "School Readiness" },
    { code: "605", title: "General Instruct. Support" },
    { code: "630", title: "Instructional Tech" },
    { code: "640", title: "Staff Development" },
    { code: "642", title: "Staff Development" },
    { code: "720", title: "Health Services" },
    { code: "760", title: "Transportation" },
    { code: "770", title: "Food Service" },
    { code: "810", title: "Operations" },
    { code: "865", title: "LTFM (Long Term Facilities)" },
    { code: "888", title: "Indoor Activities Center" },
    { code: "935", title: "Post-Employment Benefits" },
    { code: "960", title: "Other Non-Recurring (Scholarships)" },
  ],
  fin: [
    { code: "000", title: "General / Districtwide" },
    { code: "302", title: "Operating Capital" },
    { code: "303", title: "ALC (Area Learning Center)" },
    { code: "313", title: "Achievement & Integration" },
    { code: "317", title: "Basic Skills / Compensatory" },
    { code: "318", title: "Incentive" },
    { code: "335", title: "Q Comp" },
    { code: "347", title: "Physical Hazards (LTFM)" },
    { code: "363", title: "Fire Safety (LTFM)" },
    { code: "373", title: "Student Support Personnel" },
    { code: "401", title: "Title I-A" },
    { code: "419", title: "Federal Special Ed" },
    { code: "701", title: "National School Lunch Program (NSLP)" },
    { code: "707", title: "Ala Carte / Catering" },
    { code: "720", title: "Regular Transportation" },
    { code: "723", title: "Special Ed Transportation" },
    { code: "797", title: "OPEB Pay-As-You-Go Levy" },
  ],
  course: [
    { code: "000", title: "General / Default" },
    { code: "101", title: "Stadium Plaza" },
    { code: "108", title: "Media Fines" },
    { code: "109", title: "Misc Activity" },
    { code: "111", title: "Iduhapi" },
    { code: "123", title: "Math Resale" },
    { code: "125", title: "Character" },
    { code: "126", title: "Unified Breakfast Club" },
    { code: "127", title: "Hennepin County Tree Grant" },
    { code: "128", title: "Enviro Grant" },
    { code: "129", title: "Robotics" },
    { code: "131", title: "ECMC Grant" },
    { code: "136", title: "Orono Plus Insurance" },
    { code: "137", title: "Solar Boat" },
    { code: "140", title: "Math Masters" },
    { code: "160", title: "Sub - Test/Comp" },
    { code: "161", title: "Sub - Sick" },
    { code: "162", title: "Sub - Assess/Test" },
    { code: "163", title: "Sub - Field Trip" },
    { code: "164", title: "Sub - Jury Duty" },
    { code: "165", title: "Sub - Bereavement" },
    { code: "166", title: "Sub - Personal" },
    { code: "167", title: "Sub - Staff Development" },
    { code: "168", title: "Sub - OEA Release" },
    { code: "169", title: "Sub - Military" },
    { code: "199", title: "Donations" },
    { code: "214", title: "GASB 68 PERA" },
    { code: "218", title: "GASB 68 TRA" },
    { code: "280", title: "Staff Dev Grant - Vandeven" },
    { code: "281", title: "K-5 Literacy" },
    { code: "330", title: "Learning & Dev Contra" },
    { code: "333", title: "Wellness (Business Office)" },
    { code: "900", title: "Gen Athletics" },
    { code: "901", title: "OAC Spartan Strong" },
    { code: "940", title: "Newspaper Activity" },
    { code: "942", title: "Spartan Annual Activity" },
    { code: "960", title: "Student Senate" },
    { code: "963", title: "DECA Activity" },
    { code: "965", title: "Student Store Apparel" },
    { code: "969", title: "ESports" },
    { code: "SCH", title: "(Various Scholarship Codes 200-274)" },
  ],
  obj: [
    { code: "100", title: "Admin Salary" },
    { code: "140", title: "Lic Classroom Teacher" },
    { code: "141", title: "Non-Lic Classroom Personnel" },
    { code: "145", title: "Lic Substitute" },
    { code: "148", title: "Q Comp Pay" },
    { code: "152", title: "Extra Assignment Pay" },
    { code: "170", title: "Non-Instructional Support" },
    { code: "175", title: "Clerical Wages" },
    { code: "185", title: "Lic Other Salary Payment" },
    { code: "199", title: "Medical Payback" },
    { code: "210", title: "FICA" },
    { code: "214", title: "PERA" },
    { code: "218", title: "TRA" },
    { code: "220", title: "Health Insurance" },
    { code: "235", title: "Dental Insurance" },
    { code: "251", title: "HSA/HRA/FSA" },
    { code: "291", title: "Retiree Benefits" },
    { code: "305", title: "Consult/Service Fees" },
    { code: "318", title: "Printing & Publishing" },
    { code: "319", title: "Computer & Tech Services" },
    { code: "329", title: "Postage" },
    { code: "332", title: "Electricity" },
    { code: "360", title: "Contract Transportation" },
    { code: "366", title: "Travel/Conference/Training" },
    { code: "401", title: "Supply/Materials Non-Inst" },
    { code: "405", title: "Non-Instruct Software" },
    { code: "410", title: "Materials Purch for Resale" },
    { code: "430", title: "Instr Supplies-Non Indiv" },
    { code: "460", title: "Textbooks" },
    { code: "490", title: "Food" },
    { code: "530", title: "Equipment - General" },
    { code: "555", title: "Cap N-Inst Tech Hardware" },
    { code: "820", title: "Dues & Membership" },
    { code: "898", title: "Scholarships" },
  ],
}
